version: '3.8'

services:
  frontend:
    build: ../../part1/ex12/
    ports:
      - 5000:5000
  backend:
    build: ../../part1/ex13/
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis
    restart: unless-stopped
